## 1.1
a = 5
b = 6
c = a**2 + b**2
print(c)
# What if a = 10 and b = 12?
d = 10
e = 12
f = d**2 + e**2
print(f)

## 1.2
string = "TheUniversityOfManchesterFacultyofBiologyMedicineAndHealth"
print(string[3:13], string[15:25])

dna_seq = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"
print(dna_seq[137:143], dna_seq[274:280])

## 1.3

